### ISSUE TITLE
attempted relative import with no known parent package

### ISSUE THREAD

**Issue by linzuzeng** [timetag/ETA#118]
216ecdb2c38010ec495085da84ebd2fae17080bd seems to break ETA when launching directly from the debugging folder using ``python eta.py`` or ``python backend.py``

The error message is "attempted relative import with no known parent package".

I know ``python -m`` is the correct way of launching it as a package, but it always call the ETA in the Python site-packages folder instead of the current git folder.

@gyger  any idea about how to solve this?

**Comment by linzuzeng** [comment]
I tired for a while and couldn't find a good solution without making another hack, like putting ``import os, sys; sys.path.append(os.path.dirname(os.path.realpath(__file__)))`` into ``__init__.py`` and continue using regular imports. 

I have two folder of different versions of ETA for comparison, but I don't want to change PYTHONPATH or reinstall ETA every time I switch. Maybe we should still allow running individual .py files directly.

**Comment by gyger** [comment]
I would suggest installing ETA using pip install -e . in the setup folder.

This development mode installs the package while still using your files
from the folder, but it does not allow to compare two folders.

**Comment by gyger** [comment]
This is such a pain, allowing scripts and package at the same time.
Relative imports are also not the ideal way of writing python code.

Would everywhere full qualified imports work plus a h. ack again to add the current package to the sys.path.

`import etabackend.backend as backend`

we could create a local file `eta_script.py` that does this hacking and allows running from the local directory, while the default way is the "pythonic" way. 

I would then also not include that script when publishing to pypi or releasing a bundle.

**Comment by gyger** [comment]
As a reference:
https://stackoverflow.com/questions/16981921/relative-imports-in-python-3

I would suggest a file `eta_script.py` plus fully qualified imports.

```
import sys
import os
import inspect

if __name__ == '__main__':
    PACKAGE_PARENT = '..'
    SCRIPT_DIR = os.path.realpath(os.path.dirname(inspect.getfile(inspect.currentframe())))
    sys.path.append(os.path.normpath(os.path.join(SCRIPT_DIR, PACKAGE_PARENT)))

    import etabackend.backend as backend
    backend.main()
```
If you agree, I will commit this to master.

**Comment by linzuzeng** [comment]
Great! 
Please also remove other ways to launch ETA mentioned in #119

**Comment by linzuzeng** [comment]
BTW, how about other scripts? 
I mainly use VS code, which runs the individual script instead of the package by default. 

I guess I need to find how to make a ``launch.json`` so that VS Code runs ETA properly.

**Comment by gyger** [comment]
Fixed 907420f

**Comment by gyger** [comment]
> BTW, how about other scripts?
I can not follow? What scripts?

**Comment by gyger** [comment]
> I mainly use VS code, which runs the individual script instead of the package by default.
> 
> I guess I need to find how to make a `launch.json` so that VS Code runs ETA properly.

You can find more information here, how to debug a module instead of a file. `launch.json` is the way to go.
https://code.visualstudio.com/docs/python/debugging

**Comment by linzuzeng** [comment]
> 
> 
> > BTW, how about other scripts?
> > I can not follow? What scripts?

Never mind. I thought you will need many copies of this file to run each `.py` file when debugging. But then I realized that it's just my bad habit to put debug code in the ``if __name__= "__main__": ``part.

> 
> 
> > I mainly use VS code, which runs the individual script instead of the package by default.
> > I guess I need to find how to make a `launch.json` so that VS Code runs ETA properly.
> 
> You can find more information here, how to debug a module instead of a file. `launch.json` is the way to go.
> https://code.visualstudio.com/docs/python/debugging

Thank you! I have already added it to my VS Code. :)

**Comment by linzuzeng** [comment]
I just tried ``pip install -e`` and it worked. But now I found I can not uninstall the development package. It keeps saying "WARNING: Skipping etabackend as it is not installed.", but I can still call python -m etabackend 
I tried `python setup.py develop --uninstall` and also manually removed the egg-link, but the link seems to be written somewhere else.

@gyger Have encountered this before?

**Comment by linzuzeng** [comment]
Removed the ``easy-install.pth`` and solved the problem. Seems to be a issue of pip. I will try to upgrade it.
