### ISSUE TITLE
Consolidate ways to run the script

### ISSUE THREAD

**Issue by gyger** [timetag/ETA#119]
We currently have two ways of launching ETA plus __main__.py

- backend.py
- eta.py

I think one way should be chosen.

**Comment by linzuzeng** [comment]
Maybe ``__main__.py`` .

If it can't work, try ``eta.py`` as we used to launch ETA with ``python eta.py`` in versions <4.0.

**Comment by linzuzeng** [comment]
The true entry point for the backend is the main() function in backend.py, though.

**Comment by gyger** [comment]
Fixed 907420f

**Comment by gyger** [comment]
Wrong bugreport
