### ISSUE TITLE
Script panel only displays two rows of code in Firefox

### ISSUE THREAD

**Issue by afsa** [timetag/ETA#121]
**Steps to reproduce:**

1. Open the ETA github site [https://timetag.github.io/ETA/gui/src/renderer/#](https://timetag.github.io/ETA/gui/src/renderer)

2. Click on code on one of the script panels

**Expected result:**
The script panel should fill the full screen and display as many rows as possible.

**Actual result:**
![Screenshot_2020-02-14 realtime - Script Panel Designer](https://user-images.githubusercontent.com/1932358/74534182-7995ac80-4f33-11ea-827b-3f9ab04814d7.png)

**Browsers affected:**
- Chrome: no
- Firefox: yes

**Comment by linzuzeng** [comment]
Sorry for the late reply.

I can reproduce it. I also found that if you resize the browser window, it will become normal again.

**Comment by linzuzeng** [comment]
Fixed. Now it displays correctly on both Chrome and Firefox. 
If you are using the ETA Web GUI, try clearing the browser cache to get the latest version, as Github CDN might ask your browser to cache the assets files.
