### ISSUE TITLE
Notify user if essentials are missing in the Instument designer

### ISSUE THREAD

**Issue by Cyberfly100** [timetag/ETA#13]
like when an initial state is not defined there should be a warning. So far it is only showing an error on compile time. I think a full compilation is not necessary, just a check, that each arrow is labled and that an initial arrow exists.

**Comment by linzuzeng** [comment]
We could also do a full check by running a partial-compilation.  We can skip the LLVM generation part, but performs only  the graph checking and grammar checking for ETA code.

**Comment by linzuzeng** [comment]
I think ETA shows warning when clicking the file browsing button.
But I also find it doesn't show user-understandable error messages. For example, when initial is not set, it shows a long error message on the backend only.

We need to add more checks to the backend when dealing with the user inputs.

**Comment by linzuzeng** [comment]
Fixed.
