### ISSUE TITLE
backend gets stuck in 0.7

### ISSUE THREAD

**Issue by Cyberfly100** [timetag/ETA#131]
![image](https://user-images.githubusercontent.com/28017534/75181819-59d66380-573f-11ea-9f1a-4f9efc579600.png)
recipe: coutrate, code panel: all

**Comment by linzuzeng** [comment]
Looks like it stucks even before starting analysis.

**Comment by linzuzeng** [comment]
It seem that I couldn't reproduce the issue. I was using a T3 mode file, though.
Could you try 0.7.1, the current draft version?

**Comment by Cyberfly100** [comment]
my bad, I was accidentally trying to access a file via the shitty internet connection here. 0.7 works just fine.
