### ISSUE TITLE
beautify the loading and timeout page of the frontend

### ISSUE THREAD

**Issue by Cyberfly100** [timetag/ETA#136]
if no backend is present, currently the GUI looks like default html.
We should style it with bootstrap, like the rest of the GUI

**Comment by linzuzeng** [comment]
I think we can just copy some CSS from index.html

**Comment by linzuzeng** [comment]
also, I think we can get the IP and port configuration from environment variable. 

User only need to set them once and both  backend and frontend would be able to get them correctly.

**Comment by gyger** [comment]
It is fixed by lucas.
