### ISSUE TITLE
backend not found popup opens older backend

### ISSUE THREAD

**Issue by Cyberfly100** [timetag/ETA#137]
probably not an issue for people who only have a stable version of ETA installed, but since I have both a stable and experimental backend I see room for improvement here.

The popup opens the stable backend by default (0.6.5) which lives in my anaconda environment 'ETA'. It is, however, not compatible with the GUI that the popup is coming from (7.1 latest). For this I have a second anaconda environment called 'etatest'. The popup should either allow selection from environments or it should automatically compare version numbers (or both?).

**Comment by linzuzeng** [comment]
The pop up always open using ``python -m etabackend`` , currently.
I think we shouldn't scan users' computer for all versions of ETA backend. 
We can instead provide a bat file that allows users to customize the command to be executed

**Comment by linzuzeng** [comment]
fixed. Update the install.rst in the documentation for how to configure ``startbackend.bat`` for conda users.
