### ISSUE TITLE
frontend timeout while looking for backend is too fast

### ISSUE THREAD

**Issue by Cyberfly100** [timetag/ETA#138]
when I open the frontend and backend with successive double clicks, the frontend has already given up looking for the backend before the backend is ready to receive a connection. This timeout should be a bit slower, I think.

**Comment by linzuzeng** [comment]
It's the default time-out of websocket. Do you know how to configure it?

**Comment by Cyberfly100** [comment]
I found these two when checking the index.html for CSS styles:
1)
![image](https://user-images.githubusercontent.com/28017534/77159180-27512980-6aa5-11ea-9f88-abf66c2a15b2.png)
2)
![image](https://user-images.githubusercontent.com/28017534/77159229-3d5eea00-6aa5-11ea-869f-9c91b632ce67.png)
Could those be the timeouts we are looking for?

**Comment by Cyberfly100** [comment]
https://stackoverflow.com/questions/29881957/websocket-connection-timeout

**Comment by linzuzeng** [comment]
fixed by updating electron 2bf4f5855a4d7f2b92b0c4de7a0941cbdc7e5b6b
