### ISSUE TITLE
default to using just one time tag file

### ISSUE THREAD

**Issue by Cyberfly100** [timetag/ETA#140]
With the multi-file capability came the need to tell eta.run() in a dict which channel assignment should be linked to which file (or rather clips generator).
For single file use, it is however a bit unwieldy to use eta.run({'name_of_the_channel_assignment':clips_gen}) when eta.run(clips_gen) should be clear already.
I suggest to make eta.run(cutfile) default to eta.run({'timetagger':cutfile}) and RFILE([0,1,2,3]) default to RFILE(timetagger, [0,1,2,3]) to make it possible to just write the former two versions in recipes where only one file is used.

**Comment by linzuzeng** [comment]
It is supported but it shows a warning currently. We can simply mute the warning if the number of RFILE matches the number of provided generators
