### ISSUE TITLE
add hovertool to bokeh script panels

### ISSUE THREAD

**Issue by Cyberfly100** [timetag/ETA#141]
to have feature parity with pyplot we should include the hovertool in at least the static bokeh plots.
countrate should already have it so we can just copy it from there.

**Comment by Cyberfly100** [comment]
added to correlation. Unfortunately the hovertool does not work with the step-glyph, so we are back to curve

**Comment by Cyberfly100** [comment]
I found it in correlation, simulation, countrate and lifetime static displays, but not in Osci nor any of the realtime displays

**Comment by linzuzeng** [comment]
Is this fixed already, after the most recent recipe update in 0.7.5?

**Comment by Cyberfly100** [comment]
not for the ones under "more" in the recipe selector. But with the toolkit this should now be taken care of kind of automatically once these recipes catch up.
