### ISSUE TITLE
frontend version needs to be automatic

### ISSUE THREAD

**Issue by Cyberfly100** [timetag/ETA#143]
the frontend version after the update (did not work automatic, though I got impatient after 5 min) is still 7.2.0 instead of 7.3.0. This should be automatic so that it is not necessary to remember that a manual change is necessary, there.

**Comment by linzuzeng** [comment]
I seems that both ``pip install --upgrade`` and the automatic upgrading for Windows GUI upgrades ETA from 0.7.2 to 0.7.3 correctly. 


![Screenshot](https://user-images.githubusercontent.com/3583410/80934570-650ed500-8dfb-11ea-8294-2b7ab04c8fb5.PNG)

Maybe anaconda or virtualenv is doing something strange here?

**Comment by gyger** [comment]
I think you need to reload with CTRL + F5, i had similar problems. We cache the webpage in the browser, not sure if this is something we need to change.

**Comment by Cyberfly100** [comment]
seemed to work well this time. I think we can close.
