### ISSUE TITLE
Fix the automatic update of the backend

### ISSUE THREAD

**Issue by Cyberfly100** [timetag/ETA#144]
currently, the automatic update always fails for my anaconda installation. I am fine with installing it myself, but I think ETA should learn when installed initially, that I am using anaconda and just keep the frontend up to date. It could maybe show a promt to remind me to update the backend myself.

**Comment by linzuzeng** [comment]
The updating logic is hard-coded here 
https://github.com/timetag/ETA/blob/be63d452a43f77ac0561b46541b3338efac55dfc/gui/src/main/backend.js#L57

We can maybe use a .bat file instead, like
https://github.com/timetag/ETA/blob/be63d452a43f77ac0561b46541b3338efac55dfc/gui/src/main/backend.js#L105

**Comment by linzuzeng** [comment]
@Cyberfly100 The new version is in draft, could you have a test?

**Comment by linzuzeng** [comment]
Currently `startbackend.bat` uses pip to install all dependencies. It breaks anaconda installation easily if the required version matplotlib/numba is higher than the existing one installed by conda.

Can we somehow in the .bat file detect if anaconda is being used, and try install the `requirements.txt`  with codna first, ignoring the missing packages, and then try installing with pip to install the rest?

**Comment by Cyberfly100** [comment]
In my anaconda install there is a separate environment for ETA (called ETA) with only pip installed packages. Maybe we could detect if an environment called ETA (could also be specifiable by the user during install) exists and create one if not.

**Comment by linzuzeng** [comment]
Sounds complicated...
