### ISSUE TITLE
Numba Error

### ISSUE THREAD

**Issue by gyger** [timetag/ETA#145]
Today I got this Numba Error, seems something is coming upon us with
Numba 0.50.0. Should be an easy fix I guess.

Import requested from: 'numba.cgutils', please update to use 'numba.core.cgutils' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.

**Comment by Cyberfly100** [comment]
so we just replace all nb.cgutils with nb.core.cgutils?

**Comment by linzuzeng** [comment]
We didn't use `nb.cgutils`. Maybe it's a problem from numba?

**Comment by Cyberfly100** [comment]
![image](https://user-images.githubusercontent.com/28017534/84004243-8bc8aa00-a96b-11ea-8aaa-9a8edd9a6899.png)
I found it 3 times in the jit_linker.
in def ARB_PARAM_MAKER():, 
in def BytesofRecords_get(typingctx):,
in def BytesofRecords_set(typingctx, param1):.

**Comment by linzuzeng** [comment]
Sorry, I forgot 

> so we just replace all nb.cgutils with nb.core.cgutils?

Will it work after replacing?

**Comment by Cyberfly100** [comment]
haven't tried. was too afraid to break something

**Comment by gyger** [comment]
From the error message it was just an alias. So I guess it should work. Not sure though.

**Comment by linzuzeng** [comment]
Fixed this, but I get more like this. :(
 
https://github.com/timetag/ETA/runs/749882126#step:5:117

**Comment by Cyberfly100** [comment]
maybe numba 0.49 is using numba.typing itself somewhere?
