### ISSUE TITLE
automatically create header/comment for items added via the "create" menu

### ISSUE THREAD

**Issue by Cyberfly100** [timetag/ETA#15]
The resoning is that users that use the create menu are not super familliar with the program, so it should provide some more info.

E.g.:
when a histogram with name h1 and dimension (10000,16) is created it should show up as

HISTOGRAM(h1,(10000,16)) #HISTOGRAM(name, (number of bins, bin size))

this could also be done as a tooltip, but i assume that that would be way more difficult

**Comment by Cyberfly100** [comment]
This could be extended with a small icon (interactive?) to show what the function does

**Comment by linzuzeng** [comment]
The create button should really be improved. 

> HISTOGRAM(h1,(10000,16)) #HISTOGRAM(name, (number of bins, bin size))
This is easy to fix. Maybe we can also  have a live-preview of the code to be inserted.

> This could be extended with a small icon (interactive?) to show what the function does 
That is easy, we can even have animations on the CREATE dialog. But we need some nice document there. Could you help me with this part?

**Comment by linzuzeng** [comment]
fixed in RC5.2
