### ISSUE TITLE
a visualization feature for the instrument designer

### ISSUE THREAD

**Issue by Cyberfly100** [timetag/ETA#16]
This is probably a more difficult project.
There could be a time tag stream with two channels that indicates the time differences between which photon events are added to the histogram.
We considered adding this as the graphical way of programming, but it was not unambiguous. I think the other way could work though. I think maybe not for crazy complicated experiments, but for the simple ones...
Now the question is how to discriminate which ones to visualize.

**Comment by linzuzeng** [comment]
I agree it could be very hard. 

> There could be a time tag stream with two channels that indicates the time differences between which photon events are added to the histogram.

This will be greatly dependent on what kind of the analysis we want to perform. For a correlation, we can use the arrow for time interval, but we can't uses it for most of the bio-related experiments that uses the power meter mode. 

I thought about a more general version of this question, can we visualize the execution of any programs? 
The first thing I come up with is  the LabVIEW-style visualizing. 
We could do similar things for ETA by using incremetntal_cut(1,...)  to cut the file per photon and highlight the blob transition by reading out the final states from the context. If we continuously repeat that, users would see an animation. It might not be very intuitive, though.

Maybe we could find a better solution by combining the two ways above somehow :)

**Comment by linzuzeng** [comment]
close for now
