### ISSUE TITLE
drop the group feature

### ISSUE THREAD

**Issue by Cyberfly100** [timetag/ETA#21]
I said we never used it and the multiple recipe scheme kind of makes is superfluous. 
Thay say unnesessary features should be dropped before a small percentage of the user base starts to like it and gets angy when they are finally dropped because of incompatibility.

**Comment by linzuzeng** [comment]
Easy to fix.

However, are you really sure that you don't want it?
I thought it could be used for performing two different kinds of analysis on a same file. For example, we can do the correlation while seeing the stability (power-meter mode).

**Comment by Cyberfly100** [comment]
yes I know. I also kind of like it, but I end up just loading the correlation recipe and afterwards loading the power-meter recipe. It is annoying to type the filename again, but it makes the recipes less crowded

**Comment by linzuzeng** [comment]
OK, then we drop it.

**Comment by Cyberfly100** [comment]
hide by default, with option to enable in settings

**Comment by linzuzeng** [comment]
Shall we set the default group in eta.run to the group name of the running display panel?

**Comment by linzuzeng** [comment]
found a reason for using it. not dropping
