### ISSUE TITLE
List the necessary packages in a conda environment

### ISSUE THREAD

**Issue by gyger** [timetag/ETA#33]
It would be nice if the necessary packages to use my "private" site-packages folder are listed in the documentation.

**Comment by gyger** [comment]
I used the following commands to get a running environment in conda.

- `conda create -n ETA python numpy numba cython llvmlite cffi flask decorator nbformat pytz requests retrying`
- Set the side package folder in ETA_LIB path
- `C:\Users\gyger\Anaconda3\envs\ETA\Lib\site-packages`
- `pip install astunparse`
  - Unfortunately the current version uses the variable name async, not allowed in Python 3.7 was fixed in a commit (https://github.com/simonpercivall/astunparse/commit/72bcac2fc408408c7cd07043c392fd9932714604) but not released yet.
   - So one needs to fix this file manually currently.
- `pip install dash dash-renderer dash-html-components dash-core-components`

Afterwards I can run the program in the command line. I still get a funny error using the packaged software about numpy not being able to import multiarray.

**Comment by linzuzeng** [comment]
I think that the packaged ETABackend.exe can not find the DLLs for conda-modified version of numpy.
It seems that conda changed the DLL loading behavior of numpy, and simply setting a sys.path is not enoguh for that.

**Comment by linzuzeng** [comment]
I updated the documentation for dependencies of ETA.

https://eta.readthedocs.io/en/latest/installation.html

**Comment by gyger** [comment]
Ok. I'll try to package a conda repo, this will make it much easier to install for the people using conda already.

**Comment by linzuzeng** [comment]
The pip package for astunparse is fixed now. The updated version is 1.6.0 .

**Comment by linzuzeng** [comment]
ETA can be installed via pip now.

```
pip install etabackend
python -m etabackend
```

**Comment by linzuzeng** [comment]
Now ETA dropped the stupid packaged "ETABackend.exe" completely. 
Instead, it uses `pip install etabackend` like other packages in Python world. 😄

**Comment by gyger** [comment]
That is awesome to hear. Very nice, Zuzeng.

**Comment by gyger** [comment]
Good, I installed it today using a conda Environment and pip and everything worked as wanted.
