### ISSUE TITLE
Add Pathlib into the software stack and use it

### ISSUE THREAD

**Issue by gyger** [timetag/ETA#35]
Nowadays python has the pathlib library in the standard lib. (https://jefftriplett.com/2017/pathlib-is-wonderful/) I think it would be convenient to use it when working with the paths in the code files.

**Comment by linzuzeng** [comment]
Will be fixed in the next version.

**Comment by linzuzeng** [comment]
I packaged it in the latest draft build. 
Could you help testing it, see if it is fully supported?

**Comment by gyger** [comment]
I am an holiday but have time starting Monday so I'll try then.

**Comment by linzuzeng** [comment]
Fixed in RC5.5.
