### ISSUE TITLE
The simple_lifetime recipe is very broken

### ISSUE THREAD

**Issue by Cyberfly100** [timetag/ETA#37]
plotly is not working because it is trying to plot a 2d hist (has been updated on github, but seemingly has not made it into the new version yet.
bokeh is anyways broken and should be replaced by matplotlib
in the instrument designer the X lifetime uses find_start(SYNC) instead of the new start(SYNCS) or start(LAST_SYNC) or infer_start_from_stop().

**Comment by linzuzeng** [comment]
1. I triggered a new build, the plotly code should be fixed now.
2. Shall we drop support of bokeh?
3. It should be infer_start_from_stop(SYNC).

**Comment by Cyberfly100** [comment]
1) plotly seems to work again
2) bokeh in simple_lifetime has been replaced with matplotlib
3) works.

done.
