### ISSUE TITLE
Provide a generic file format you support

### ISSUE THREAD

**Issue by gyger** [timetag/ETA#40]
It would be nice to have a generic file format. E.g. hdf5 with a defined structure that you support aswell. This would allow to read data that was collected differently.

**Comment by linzuzeng** [comment]
We support Swebian Instrument timetag format, which is already pretty "generic". It is a binary file with no header, and the timetags was converted to picosecond. 

We can add support to hdf5, but we need to first define the timetag format (unit for time, channel number assignment) with hdf5.

**Comment by gyger** [comment]
I was thinking about a file format that is easy to create in e.g. python. 
The problem with the swabian Timeformat is it gets pretty large fast due to the excessive use of storage especially with the sync laser.

**Comment by Cyberfly100** [comment]
The most useful file formats I have come across so far are picoQuants T3 and SwabianInstruments (with hardware filter enabled) file format. We could support T3 also with a minimal header and provide a mini script showing how to create a working file. Same for the SwabianInstruments file.

**Comment by linzuzeng** [comment]
We can add an Action for writing to a "sink" device that is write-only. Users can later retrive all the events (including channel# and time) of this device form Python side and write with arbitrarty format that he want to use.
Should be useful for storing the simulation results.

`eta.writetags(ctx,filename="test1.tags",sink="sinkdev1")`

**Comment by linzuzeng** [comment]
Fixed in 5ee2ffe4ed876af697d04f3fbd382bd16dbc6baf
