### ISSUE TITLE
change the channels numbers directly on the main GUI

### ISSUE THREAD

**Issue by linzuzeng** [timetag/ETA#81]
It would be WAY easier if you could just change the channels numbers directly on the main GUI...

**Comment by gyger** [comment]
No, I am against this feature. It makes too many knobs available.

**Comment by linzuzeng** [comment]
Once I need to change all the chn0 to chn3 and I ended up clicking on Instrument Designer a million times. 

But I agree that this is not often used. And users who really need do do this can simply do a text replacement in the ``.eta`` or ``.instr`` file, which are bascially JSON files.
