### ISSUE TITLE
Integrate into jupyter lab

### ISSUE THREAD

**Issue by gyger** [timetag/ETA#88]
This is just an idea, to make ETA usable inside jupyter lab and continue working with the results in the notebook below.

**Comment by linzuzeng** [comment]
Very good idea! The Python part of ETA should be able to work without too many modifications. I will write some document for how to call those ETA APIs like eta.run() from any Python environment without using the the ETA Backend.

But I am worrying that the existing GUI might not work easily as a [Jupyter Front-End Shell](https://jupyterlab.readthedocs.io/en/stable/developer/extension_dev.html).

I would recommend to use [ETA Web GUI](https://timetag.github.io/ETA/gui/src/renderer/) for now.

**Comment by gyger** [comment]
I just found [JDaviz](https://github.com/spacetelescope/jdaviz), that is a spectra analysis platform within jupyter. Could be useful if we want to look at how they implement gui parts that work within jupyter.

**Comment by linzuzeng** [comment]
Sounds like a lot of work. Doesn't bokeh work in jupyter?

**Comment by gyger** [comment]
No that works fine, just in case we want to have the state machine designer within jupyter. I think for now we can leave that issue closed. Just wanted to have that example documented.
