### ISSUE TITLE
wait_till_presnese: Name is weird and should have verbose=False

### ISSUE THREAD

**Issue by gyger** [timetag/ETA#93]
I think the Name is a spelling mistake and it would be nice to have a verbose parameter for this function.

**Comment by linzuzeng** [comment]
Thanks. But I think the name is still weird after correcting the typo. Users can't guess what it is doing from its name.

Could you maybe suggest a better name?

**Comment by Cyberfly100** [comment]
In commit [c7978](https://github.com/timetag/ETA/commit/c7978adb62cd0aae1eac62712b912be74ae50bd3), I changed the name from `wait_till_presence` to `wait_for_data`. I also corrected a typo in a variable name inside the function.
Still has to be tested.

**Comment by linzuzeng** [comment]
I think it is better. We also need to update the documentation before close the issue.

**Comment by Cyberfly100** [comment]
We were also considering await instead of wait_for, but await typically returns data already. I updated the documentation with the new name and the verbose argument.

**Comment by Cyberfly100** [comment]
tested, it works.
